# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.20.6
neo_version=20.6.112-beta
neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.06.02
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.angrymobs
mod_id=angrymobs
mod_archive_name=AngryMobs

#Publishing
mod_name=Angry Mobs
curseforge_id=430225
modrinth_id=W9PF5nLR

# Version
version=6.0.0

# Dependencies
jei_version=17.3.0.49
crafttweaker_version=19.0.8