modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/AngryMobs/issues"
license="MIT"

[[mods]]
modId="angrymobs"
version="${file.jarVersion}"
displayName="Angry Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/angry-mobs"
authors="Mrbysco, ShyNieke"
credits="GentlemanGnu for the idea"
description='''
Allows a pack developer to add additional AI goals to existing mobs
'''
[[dependencies.angrymobs]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.angrymobs]]
modId="neoforge"
type="required"
versionRange="[21.0.143,)"
ordering="NONE"
side="BOTH"